[package]
name = "leetcode_rs"
version = "0.2.0"
authors = []
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
automod = { path = "automod" }
test-case = "2.0.0"
